services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  django-backend:
    build: .
    command: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      DB_NAME: notes_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres-db
      DB_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  postgres_data: